on:
  pull_request:
    types:
      - opened

jobs:
  test-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull_requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Post PR Comment
        uses: ./
        with:
          gh_token: ${{ secrete.GH_TOKEN }}
          giphy_api_key: ${{ secrets.GIPHY_API_KEY }}